package com.example.weatherapplication.model

data class LocalNames(
    val ar: String,
    val bn: String,
    val cs: String,
    val de: String,
    val el: String,
    val en: String,
    val eo: String,
    val es: String,
    val fa: String,
    val fr: String,
    val he: String,
    val hi: String,
    val ja: String,
    val kn: String,
    val ko: String,
    val ku: String,
    val lv: String,
    val ml: String,
    val ms: String,
    val my: String,
    val ne: String,
    val oc: String,
    val pa: String,
    val pt: String,
    val ru: String,
    val ta: String,
    val te: String,
    val th: String,
    val uk: String,
    val ur: String,
    val zh: String
)